# Generated by Django 2.1.5 on 2019-02-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_auto_20190131_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
