# Generated by Django 2.1.5 on 2019-02-01 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20190131_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='path',
        ),
    ]
