# Generated by Django 2.1.7 on 2019-02-18 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_nav_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='link',
            field=models.SlugField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Nav'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
