# Generated by Django 2.1.7 on 2019-02-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0011_auto_20190217_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintext',
            name='text_type',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Main Page', 'Main')], default='Draft',
                                   max_length=254),
        ),
        migrations.AlterField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Nav'),
        ),
    ]
