# Generated by Django 2.1.7 on 2019-02-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_auto_20190217_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintext',
            name='text_type',
            field=models.CharField(
                choices=[('Draft', 'Draft'), ('Main Page', 'Main'), ('Footer', 'Footer'), ('Base Title', 'Base Title'),
                         ('Default Title', 'Default Title')], default='Draft', max_length=254),
        ),
        migrations.AlterField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='children',
                                    to='blog.Nav'),
        ),
    ]
