# Generated by Django 2.1.7 on 2019-03-09 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_auto_20190218_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'permissions': (('files_gui_own_create', 'Can upload files via the GUI'),
                                     ('files_gui_own_delete', 'Can delete their own files via the GUI'),
                                     ('files_gui_own_list', 'Can view their own list of files via the GUI'),
                                     ('files_gui_all_delete', "Can delete all user's files via the GUI"),
                                     ('files_gui_all_list', "Can view all user's list of files via the GUI")),
                     'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='files',
            name='fil',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Owner'),
        ),
    ]
