# Generated by Django 2.1.7 on 2019-03-09 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0015_auto_20190309_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('post_gui_can_post', 'Can create new posts via the GUI'),
                                     ('post_gui_can_update', 'Can update own posts via the GUI'),
                                     ('post_gui_can_delete', 'Can delete own posts via the GUI'))},
        ),
    ]
