# Generated by Django 2.1.7 on 2019-09-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20190309_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='meeting start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='meeting end time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('meeting_gui_can_create', 'Can create new meetings via the GUI'),),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, verbose_name='member name')),
                ('slack', models.CharField(max_length=4096, verbose_name='slack id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='user added')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='user modified')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='sign-in time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='sign-out time')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Member')),
            ],
        ),
    ]
