# Generated by Django 2.1.7 on 2019-09-28 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0017_meeting_member_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='meeting end time'),
        ),
    ]
