# Generated by Django 2.2.6 on 2019-11-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0020_auto_20191019_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='meeting end time'),
        ),
    ]
