# Generated by Django 2.2.6 on 2019-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0021_auto_20191103_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slack',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='slack id'),
        ),
    ]
