# Generated by Django 2.2.6 on 2019-11-03 15:53

import blog.models.signin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0023_historicalmeeting_historicalmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, validators=[blog.models.signin.Signin.endValidator],
                                       verbose_name='sign-out time'),
        ),
        migrations.CreateModel(
            name='HistoricalSignin',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time',
                 models.DateTimeField(blank=True, editable=False, validators=[blog.models.signin.Signin.startValidator],
                                      verbose_name='sign-in time')),
                ('end_time',
                 models.DateTimeField(blank=True, null=True, validators=[blog.models.signin.Signin.endValidator],
                                      verbose_name='sign-out time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                              on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                              to='blog.Meeting')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                           to='blog.Member')),
            ],
            options={
                'verbose_name': 'historical signin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
