# Generated by Django 2.2.10 on 2020-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20191123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='team',
            field=models.CharField(choices=[('None', 'None'), ('Software', 'Software'), ('CAD/Manufacturing', 'CAD/Manufacturing'), ('Outreach', 'Outreach'), ('Strategy', 'Strategy'), ('Safety', 'Safety'), ('Helping Hands', 'Helping Hands'), ('Sponsorship', 'Sponsorship'), ('Graphics/Spirit', 'Graphics/Spirit'), ('Comun/Website', 'Comun/Website'), ('Visuals', 'Visuals')], default='None', max_length=255, verbose_name='team name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('None', 'None'), ('Software', 'Software'), ('CAD/Manufacturing', 'CAD/Manufacturing'), ('Outreach', 'Outreach'), ('Strategy', 'Strategy'), ('Safety', 'Safety'), ('Helping Hands', 'Helping Hands'), ('Sponsorship', 'Sponsorship'), ('Graphics/Spirit', 'Graphics/Spirit'), ('Comun/Website', 'Comun/Website'), ('Visuals', 'Visuals')], default='None', max_length=255, verbose_name='team name'),
        ),
    ]
