# Generated by Django 3.0.2 on 2020-02-15 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_auto_20191212_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='subteam',
        ),
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical team',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='team',
            field=models.ForeignKey(default="None", on_delete=django.db.models.deletion.CASCADE, to='blog.Team',
                                    verbose_name='team name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, default='None', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.Team', verbose_name='team name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Team', verbose_name='team name'),
        ),
    ]
