# Generated by Django 3.0.3 on 2020-02-15 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0026_auto_20191212_1825'),
    ]

    operations = [
    ]
