# Generated by Django 3.0.3 on 2020-02-15 19:47
from django.core.management import call_command

from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', "teams", app_label='blog')


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0028_auto_20200215_1446'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
